# Generated by Django 2.2.1 on 2019-06-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190619_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
    ]
