# Generated by Django 2.2.1 on 2019-06-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190619_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(default='ComicBookRider', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
